Adicionado login/logout para admins
TreinaDev/payment-antifraud pull request #12
Opened 2022-11-03 19:39 UTC by minccia

Adicionada função de login/logout para admins com a gem 'Devise'

2022-11-03 20:44 UTC, joaorsalmeida commented on spec/system/admin/admin_login_spec.rb
> +	visit new_admin_session_path
Essa indentação me parece meio esquisita. Está certinha, com 2 espaços?

2022-11-03 20:45 UTC, joaorsalmeida commented on spec/system/admin/admin_login_spec.rb
> +	expect(page).to have_content 'Olá Petra Paola - petrapaola@email.com'
Aqui também ficou estranho 🤔

2022-11-03 20:45 UTC, joaorsalmeida reviewed
Podem conferir se a formatação do código dos testes está ok mesmo?

2022-11-04 15:01 UTC, joaorsalmeida commented on app/views/layouts/application.html.erb
> +          <%= 'Aguardando aprovação do administrador do sistema.' %>
Não é preciso essa tag de impressão `<%=` aqui né?!

2022-11-04 15:02 UTC, joaorsalmeida commented on config/initializers/locale.rb
> +I18n.available_locales = [:en, :'pt-BR']
Vamos ter opção em inglês? Não acho necessário e com isso podemos deixar somente 'pt-BR' na lista de opções disponíveis.

2022-11-04 15:03 UTC, joaorsalmeida requested changes
A formatação dos testes continua toda bagunçada pra mim :(

2022-11-04 16:13 UTC, petragrunheidt commented on app/views/layouts/application.html.erb
> +          <%= 'Aguardando aprovação do administrador do sistema.' %>
De qual você ta falando joão? acho que elas são necessárias sim

2022-11-04 17:02 UTC, petragrunheidt commented on app/views/layouts/application.html.erb
> +          <%= 'Aguardando aprovação do administrador do sistema.' %>
ahh entendi, esquece kk

2022-11-04 17:48 UTC, minccia commented on config/initializers/locale.rb
> +I18n.available_locales = [:en, :'pt-BR']
Ok João, vou estar removendo o :en, obrigada.

2022-11-04 18:12 UTC, petragrunheidt commented
resolves #2 
resolves #3

2022-11-04 20:45 UTC, joaorsalmeida approved these changes

2022-11-04 20:46 UTC, merged