Editar uma promoção
TreinaDev/payment-antifraud pull request #21
Opened 2022-11-07 21:39 UTC by luizarodrigues98

choose #14 
Co-authored-by: ana-borowsky <ana-borowsky@users.noreply.github.com>

2022-11-08 15:59 UTC, joaorsalmeida reviewed
Me parece bem encaminhado, o que falta para fecharmos?

2022-11-08 19:41 UTC, joaorsalmeida requested changes
Só faltou ter mais um teste unitário pra ficar ok, deixei o comentário no arquivo do teste.

2022-11-08 19:41 UTC, joaorsalmeida commented on spec/models/promo_spec.rb
> +    it 'a data final deve ser maior que a inicial' do
Pra ficar ok só faltou ter um teste inverso, que garante que existe um erro/problema ao cadastrar a data final menor que a data inicial.

2022-11-09 13:46 UTC, joaorsalmeida requested changes

2022-11-09 14:31 UTC, luizarodrigues98 commented on app/views/promos/edit.html.erb
> +<%= form_with(model: @promo, url: promo_path(@promo.id)) do |f| %>
Certo, vou alterar agora. Obrigada João!!

2022-11-09 18:23 UTC, merged