Promo expiration
TreinaDev/payment-antifraud pull request #51
Opened 2022-11-17 01:12 UTC by petragrunheidt

resolves #50

2022-11-17 13:52 UTC, joaorsalmeida requested changes

2022-11-17 13:52 UTC, joaorsalmeida commented on config/apis.yml
> +  insurance_api_first_product_endpoint: https://mocki.io/v1/42fd6be9-6747-42b0-91ee-7132bd78e68d
Isso não faz sentido. As configurações devem ser idênticas em todos ambientes, só mudam os valores.

2022-11-17 13:52 UTC, joaorsalmeida commented on spec/requests/apis/promo_api_spec.rb
> -      get '/api/v1/promos/3MVGTOVW'
Parece que houve uma mudança no acesso à API neste endpoint, certo? Então precisamos incluir nesse Pull Request a atualização da documentação para os demais times consumirem.

2022-11-17 13:53 UTC, petragrunheidt commented on config/apis.yml
> +  insurance_api_first_product_endpoint: https://mocki.io/v1/42fd6be9-6747-42b0-91ee-7132bd78e68d
esqueci de deletar isso, a gente acabou nem usando no fim

2022-11-17 13:54 UTC, petragrunheidt commented on spec/requests/apis/promo_api_spec.rb
> -      get '/api/v1/promos/3MVGTOVW'
joão, eu atualizei a wiki, mas o link no readme é o mesmo

https://github.com/TreinaDev/payment-antifraud/wiki/API-para-obter-promo%C3%A7%C3%B5es-de-cada-seguradora

2022-11-18 16:51 UTC, joaorsalmeida approved these changes
Lembrei pq eu não gosto de Wiki como documentação haha

2022-11-18 16:57 UTC, merged