consome via API nome do Pacote e da seguradora para aparecer na cobrança
TreinaDev/payment-antifraud pull request #92
Opened 2022-11-23 19:08 UTC by luizarodrigues98

closes #89

2022-11-23 22:12 UTC, joaorsalmeida requested changes
Senti falta de tratamento de erro no consumo da API externa e também coloquei uma sugestão de nomes diferentes para os métodos do model .

2022-11-23 22:12 UTC, joaorsalmeida commented on app/models/invoice.rb
> +  def get_insurance_company_id
Se o método retorna name ele nao poderia se chamar `insurance_company_name`?

2022-11-23 22:12 UTC, joaorsalmeida commented on app/models/invoice.rb
> +  def get_package_id
O mesmo aqui

2022-11-24 14:20 UTC, luizarodrigues98 commented on app/models/invoice.rb
> +  def get_insurance_company_id
Bom dia, Bruna ajeitou e ficou assim: name_insurance_company

2022-11-24 14:20 UTC, luizarodrigues98 commented on app/models/invoice.rb
> +  def get_package_id
o daqui ficou name_package

2022-11-25 01:11 UTC, joaorsalmeida approved these changes

2022-11-25 13:03 UTC, merged